apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-mojaloop-java"
  labels:
    app: ph-ee-connector-mojaloop-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-mojaloop-java
  template:
    metadata:
      labels:
        app: ph-ee-connector-mojaloop-java
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: ph-ee-connector-mojaloop-java
          image: paymenthubee.mifos.io:5000/phee/connector-mojaloop-java
          ports:
            - containerPort: 5000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_mojaloop.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mojaloop-java
  name: ph-ee-connector-mojaloop-java
  namespace: default
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-mojaloop-java
  sessionAffinity: None
  type: ClusterIP
