{{- if .Values.operations.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-importer-es
  labels:
    app: ph-ee-importer-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-importer-es
  template:
    metadata:
      labels:
        app: ph-ee-importer-es
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: ph-ee-importer-es
          image: paymenthubee.mifos.io:5000/phee/importer-es

{{- end }}
