{{- if .Values.operations.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-operations-app"
  labels:
    app: ph-ee-operations-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-operations-app
  template:
    metadata:
      labels:
        app: ph-ee-operations-app
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      imagePullSecrets:
      - name: regcred

      containers:
        - name: ph-ee-operations-app
          image: paymenthubee.mifos.io:5000/phee/operations-app
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /oauth/token_key
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: "FINERACT_DATASOURCE_CORE_USERNAME"
              value: "mifos"
            - name: "FINERACT_DATASOURCE_CORE_PASSWORD"
              value: "password"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_operations_app.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-operations-app
  name: ph-ee-operations-app
  namespace: default
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-operations-app
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ph-ee-operations-app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: "{{ .Values.ph_ee_operations_app.hostname }}"
      http:
        paths:
          - backend:
              serviceName: ph-ee-operations-app
              servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ph-ee-identity
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: "{{ .Values.ph_ee_identity.hostname }}"
      http:
        paths:
          - backend:
              serviceName: ph-ee-operations-app
              servicePort: 80

{{- end }}
